name: crestaurant2
description: Submission Fundamental Flutter

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.2.9
  flutter_svg: ^1.1.4
  page_transition: ^2.0.9
  flutter_rating_bar: ^4.0.1
  fluttertoast: ^8.0.9
  provider: ^6.0.3
  http: ^0.13.5
  connectivity_plus: ^2.3.6+1
  shimmer: ^2.0.0
  expandable_text: ^2.3.0
  shared_preferences: ^2.0.15
  android_alarm_manager_plus: ^2.0.2
  sqflite: ^2.0.3+1
  flutter_slidable: ^2.0.0
  flutter_local_notifications: ^9.7.0
  intl: ^0.17.0
  rxdart: ^0.27.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.1
  build_runner: ^2.2.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/data/
    - assets/icons/
    - assets/data/
    - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/gsBlack.ttf
        - asset: assets/fonts/gsBlackItalic.ttf
        - asset: assets/fonts/gsBold.ttf
        - asset: assets/fonts/gsBoldItalic.ttf
        - asset: assets/fonts/gsItalic.ttf
        - asset: assets/fonts/gsLightItalic.ttf
        - asset: assets/fonts/gsMedium.ttf
        - asset: assets/fonts/gsMediumItalic.ttf
        - asset: assets/fonts/gsRegular.ttf
        - asset: assets/fonts/gsThin.ttf
        - asset: assets/fonts/gsThinItalic.ttf
flutter_native_splash:
  color: '#FFFFFF'
  fullscreen: true
  image: assets/images/logo_splash_screen.png
